---

- name: Check if setuptools is already installed
  stat: path=/usr/local/bin/easy_install-2.7
  register: setuptools

- name: Download Setuptools
  get_url: url=https://pypi.python.org/packages/source/s/setuptools/setuptools-5.7.tar.gz
           dest={{ tmp_dir }}/setuptools-5.7.tar
  when: not setuptools.stat.exists

- name: Unpack Setuptools
  unarchive: src={{ tmp_dir }}/setuptools-5.7.tar dest={{ tmp_dir }} copy=no
  when: not setuptools.stat.exists

- name: Install Setuptools
  command: /usr/local/bin/python2.7 setup.py install chdir={{ tmp_dir }}/setuptools-5.7
  when: not setuptools.stat.exists
